-- ==========================================================
-- ATUALIZAÇÃO 17 — Termo do dia, Onboarding, Modo escuro, Mural de conquistas
-- Cole este arquivo INTEIRO no SQL Editor do Supabase e clique em Run.
-- ==========================================================

-- ==========================================================
-- 1) TERMO DO DIA
-- ==========================================================
create table if not exists public.word_of_day (
  day_index int primary key check (day_index between 1 and 365),
  term text not null,
  definition text not null,
  example text not null
);

alter table public.word_of_day enable row level security;

drop policy if exists "word_of_day_select" on public.word_of_day;
create policy "word_of_day_select" on public.word_of_day
  for select using ( auth.uid() is not null );

drop policy if exists "word_of_day_insert" on public.word_of_day;
create policy "word_of_day_insert" on public.word_of_day
  for insert with check ( public.is_admin() );

drop policy if exists "word_of_day_update" on public.word_of_day;
create policy "word_of_day_update" on public.word_of_day
  for update using ( public.is_admin() );

drop policy if exists "word_of_day_delete" on public.word_of_day;
create policy "word_of_day_delete" on public.word_of_day
  for delete using ( public.is_admin() );

insert into public.word_of_day (day_index, term, definition, example) values
(1, 'get up', 'to leave your bed after sleeping', 'I usually get up at seven.'),
(2, 'achieve', 'to successfully reach a goal or result', 'The team achieved its target.'),
(3, 'absolute', 'complete and not limited', 'The silence was absolute during the exam.'),
(4, 'go to bed', 'to go to your bed to sleep', 'I go to bed around eleven.'),
(5, 'adapt', 'to change in order to suit a new situation', 'She adapted quickly to the new role.'),
(6, 'accumulate', 'to gradually gather or build up', 'Small errors can accumulate over time.'),
(7, 'wake up', 'to stop sleeping', 'I wake up early on weekdays.'),
(8, 'admit', 'to accept that something is true', 'He admitted his mistake.'),
(9, 'acknowledge', 'to accept or recognize that something is true', 'She acknowledged the limitations of the study.'),
(10, 'have breakfast', 'to eat the first meal of the day', 'I have breakfast before work.'),
(11, 'afford', 'to have enough money or time for something', 'We can''t afford to waste time.'),
(12, 'advocate', 'to publicly support an idea or action', 'They advocate greater transparency.'),
(13, 'have lunch', 'to eat the meal usually eaten around midday', 'We have lunch at noon.'),
(14, 'announce', 'to make something known publicly', 'The company announced the new policy.'),
(15, 'albeit', 'although; even though', 'The solution was effective, albeit expensive.'),
(16, 'have dinner', 'to eat the evening meal', 'We have dinner together.'),
(17, 'appreciate', 'to recognize the value of something', 'I appreciate your help.'),
(18, 'ambiguous', 'having more than one possible meaning', 'The wording is ambiguous.'),
(19, 'go home', 'to return to your home', 'I go home at six.'),
(20, 'approach', 'a way of dealing with a situation', 'We need a different approach.'),
(21, 'ambivalence', 'mixed feelings about something', 'He felt ambivalence about the decision.'),
(22, 'come back', 'to return to a place', 'I''ll come back after lunch.'),
(23, 'approve', 'to officially accept something', 'The director approved the budget.'),
(24, 'analogy', 'a comparison used to explain an idea', 'The teacher used an analogy to explain the process.'),
(25, 'sit down', 'to move into a sitting position', 'Please sit down.'),
(26, 'argue', 'to give reasons for or against something', 'They argued about the best solution.'),
(27, 'anticipate', 'to expect something and prepare for it', 'We anticipate higher demand next year.'),
(28, 'stand up', 'to move into a standing position', 'Everyone stood up when she entered.'),
(29, 'avoid', 'to stay away from something or prevent it', 'Try to avoid unnecessary delays.'),
(30, 'arbitrary', 'based on personal choice rather than a clear reason', 'The rule seemed arbitrary.'),
(31, 'turn on', 'to start a machine or light', 'Please turn on the computer.'),
(32, 'aware', 'knowing about something', 'Are you aware of the risks?'),
(33, 'articulate', 'to express an idea clearly and effectively', 'She articulated the problem very well.'),
(34, 'turn off', 'to stop a machine or light', 'Turn off the lights before you leave.'),
(35, 'benefit', 'a positive effect or advantage', 'The main benefit is flexibility.'),
(36, 'assess', 'to evaluate something carefully', 'We need to assess the risks.'),
(37, 'put on', 'to place clothes on your body', 'Put on your jacket; it''s cold.'),
(38, 'challenge', 'a difficult task or situation', 'Time is our biggest challenge.'),
(39, 'attain', 'to succeed in reaching a goal', 'The team attained its objective.'),
(40, 'take off', 'to remove clothes', 'You can take off your coat here.'),
(41, 'compare', 'to examine things to see how they are similar or different', 'Let''s compare the two options.'),
(42, 'authenticity', 'the quality of being genuine', 'The museum verified the painting''s authenticity.'),
(43, 'look for', 'to try to find something', 'I''m looking for my keys.'),
(44, 'complain', 'to say that you are unhappy about something', 'Several customers complained about the service.'),
(45, 'autonomy', 'the freedom to make decisions independently', 'The role offers considerable autonomy.'),
(46, 'look at', 'to direct your eyes toward something', 'Look at this picture.'),
(47, 'concentrate', 'to give all your attention to something', 'I need to concentrate on this task.'),
(48, 'bias', 'a tendency that unfairly affects judgment', 'The study may contain some bias.'),
(49, 'listen to', 'to pay attention to a sound', 'Listen to this song.'),
(50, 'confirm', 'to show that something is true or correct', 'Please confirm the meeting time.'),
(51, 'bolster', 'to support or strengthen something', 'The evidence bolstered the argument.'),
(52, 'talk to', 'to speak with someone', 'I need to talk to my manager.'),
(53, 'consider', 'to think carefully about something', 'We are considering another option.'),
(54, 'coherent', 'logical and well organized', 'Her explanation was coherent and convincing.'),
(55, 'wait for', 'to stay until someone or something arrives', 'I''m waiting for the bus.'),
(56, 'contain', 'to have something inside', 'The report contains useful information.'),
(57, 'coincide', 'to happen at the same time or correspond', 'The two events coincided.'),
(58, 'ask for', 'to request something', 'She asked for some help.'),
(59, 'contribute', 'to help cause or develop something', 'Training contributes to better performance.'),
(60, 'compelling', 'very convincing or persuasive', 'The report provides compelling evidence.'),
(61, 'help', 'to make something easier for someone', 'Can you help me with this?'),
(62, 'convince', 'to make someone believe that something is true', 'The data convinced the manager.'),
(63, 'comprehensive', 'including all or nearly all relevant details', 'The review was comprehensive.'),
(64, 'choose', 'to decide which thing you want', 'You can choose any seat.'),
(65, 'cope with', 'to manage a difficult situation', 'She learned to cope with the workload.'),
(66, 'concede', 'to admit that something is true, often reluctantly', 'He conceded that the plan had risks.'),
(67, 'buy', 'to get something by paying for it', 'I need to buy some bread.'),
(68, 'deal with', 'to handle a problem or situation', 'We need to deal with the complaint.'),
(69, 'conceive', 'to develop or imagine an idea', 'They conceived a new approach.'),
(70, 'sell', 'to give something to someone for money', 'They sell fresh fruit here.'),
(71, 'depend on', 'to be decided or affected by something', 'It depends on the weather.'),
(72, 'concurrent', 'happening at the same time', 'The two projects ran concurrently.'),
(73, 'pay', 'to give money for something', 'I''ll pay for dinner.'),
(74, 'develop', 'to grow or create something over time', 'She developed a new process.'),
(75, 'constrain', 'to limit what is possible', 'Budget constraints may constrain growth.'),
(76, 'cost', 'to have a particular price', 'How much does it cost?'),
(77, 'discuss', 'to talk about something in detail', 'Let''s discuss the results.'),
(78, 'contemplate', 'to consider something carefully', 'We''re contemplating a major change.'),
(79, 'spend', 'to use money or time', 'I spend two hours studying.'),
(80, 'effective', 'successful in producing the intended result', 'The training was effective.'),
(81, 'contradict', 'to state that something is not true or does not agree', 'The figures contradict the earlier report.'),
(82, 'save', 'to keep money or something for later', 'I''m saving money for a trip.'),
(83, 'efficient', 'working well without wasting time or resources', 'The new process is more efficient.'),
(84, 'conventional', 'based on what is traditionally accepted', 'They chose a conventional approach.'),
(85, 'use', 'to do something with a thing for a purpose', 'We use this room for meetings.'),
(86, 'encourage', 'to give someone confidence or support to do something', 'The manager encouraged the team to speak up.'),
(87, 'controversial', 'causing disagreement or strong opposing opinions', 'The proposal remains controversial.'),
(88, 'need', 'to require something', 'We need more time.'),
(89, 'estimate', 'to calculate an amount approximately', 'We estimate the cost at $5,000.'),
(90, 'credible', 'able to be believed or trusted', 'We need a credible source.'),
(91, 'want', 'to have a desire for something', 'I want a cup of coffee.'),
(92, 'experience', 'knowledge gained through doing something', 'She has experience in sales.'),
(93, 'crucial', 'extremely important', 'Timing is crucial to success.'),
(94, 'like', 'to enjoy something', 'I like this restaurant.'),
(95, 'explain', 'to make something clear', 'Can you explain the difference?'),
(96, 'cumulative', 'increasing as more parts are added', 'The cumulative effect was significant.'),
(97, 'love', 'to like something very much', 'She loves classical music.'),
(98, 'focus on', 'to give particular attention to something', 'Let''s focus on the main issue.'),
(99, 'deliberate', 'done intentionally and carefully', 'The change was deliberate.'),
(100, 'hate', 'to dislike something very much', 'I hate waking up early.'),
(101, 'improve', 'to make or become better', 'The update improved performance.'),
(102, 'diminish', 'to become smaller or less important', 'The impact gradually diminished.'),
(103, 'know', 'to have information in your mind', 'I know the answer.'),
(104, 'include', 'to contain something as a part', 'The price includes delivery.'),
(105, 'discrete', 'separate and distinct', 'The system has several discrete modules.'),
(106, 'think', 'to have an opinion or idea', 'I think you''re right.'),
(107, 'increase', 'to become or make greater', 'Sales increased this month.'),
(108, 'disparity', 'a significant difference between people or things', 'There is a large disparity in access.'),
(109, 'understand', 'to know the meaning of something', 'I understand your question.'),
(110, 'influence', 'to affect the way someone or something develops', 'Weather can influence demand.'),
(111, 'distort', 'to change something so that it is no longer accurate', 'The statistic can distort the picture.'),
(112, 'remember', 'to keep something in your mind', 'Remember to call your mother.'),
(113, 'involve', 'to include someone or something as a necessary part', 'The job involves working with customers.'),
(114, 'diversify', 'to develop a wider range of products or activities', 'The company diversified its services.'),
(115, 'forget', 'to fail to remember something', 'Don''t forget your passport.'),
(116, 'manage', 'to control or organize something successfully', 'She manages a large team.'),
(117, 'elaborate', 'to give more details about something', 'Could you elaborate on that point?'),
(118, 'learn', 'to gain knowledge or a skill', 'I''m learning Spanish.'),
(119, 'mention', 'to refer to something briefly', 'He mentioned the problem in the meeting.'),
(120, 'empirical', 'based on observation or experiment', 'The claim lacks empirical support.'),
(121, 'teach', 'to help someone learn', 'She teaches English online.'),
(122, 'notice', 'to become aware of something', 'Did you notice the change?'),
(123, 'encompass', 'to include a wide range of things', 'The project encompasses several departments.'),
(124, 'study', 'to spend time learning about something', 'He studies every evening.'),
(125, 'obtain', 'to get something, especially through effort', 'We obtained approval yesterday.'),
(126, 'enhance', 'to improve the quality or value of something', 'The update enhances performance.'),
(127, 'work', 'to do a job or activity', 'I work from home.'),
(128, 'offer', 'to say that you are willing to give or do something', 'They offered me a job.'),
(129, 'exacerbate', 'to make a problem worse', 'The delay exacerbated the problem.'),
(130, 'start', 'to begin something', 'The class starts at eight.'),
(131, 'participate', 'to take part in something', 'Everyone participated in the discussion.'),
(132, 'facilitate', 'to make an action or process easier', 'The platform facilitates collaboration.'),
(133, 'finish', 'to complete something', 'I finished the report.'),
(134, 'perform', 'to do a task or function', 'The system performs well.'),
(135, 'feasible', 'possible and practical to do', 'The proposal is financially feasible.'),
(136, 'stop', 'to end an activity', 'Let''s stop for a break.'),
(137, 'prevent', 'to stop something from happening', 'The checklist helps prevent errors.'),
(138, 'fluctuate', 'to change frequently, especially between levels', 'Prices fluctuate throughout the year.'),
(139, 'continue', 'to keep doing something', 'Please continue reading.'),
(140, 'provide', 'to give something needed', 'The company provides training.'),
(141, 'formulate', 'to develop a plan or idea carefully', 'The team formulated a new strategy.'),
(142, 'change', 'to make or become different', 'We need to change the plan.'),
(143, 'recommend', 'to advise someone to do something', 'I recommend checking the figures.'),
(144, 'foster', 'to encourage the development of something', 'The program fosters innovation.'),
(145, 'move', 'to go to a different place', 'We moved to a new office.'),
(146, 'reduce', 'to make something smaller or less', 'We need to reduce waste.'),
(147, 'framework', 'a structure used to organize ideas or processes', 'We need a clear decision-making framework.'),
(148, 'arrive', 'to reach a place', 'What time did you arrive?'),
(149, 'refer to', 'to mention or direct attention to something', 'The report refers to last year''s data.'),
(150, 'fundamental', 'basic and extremely important', 'Trust is fundamental to teamwork.'),
(151, 'leave', 'to go away from a place', 'I need to leave now.'),
(152, 'rely on', 'to depend on someone or something', 'We rely on accurate information.'),
(153, 'hence', 'for this reason; therefore', 'The evidence was weak; hence, we delayed the decision.'),
(154, 'meet', 'to come together with someone', 'Let''s meet tomorrow.'),
(155, 'require', 'to need something', 'The position requires experience.'),
(156, 'hierarchy', 'a system in which people or things are ranked', 'The company has a clear hierarchy.'),
(157, 'visit', 'to go somewhere for a short time', 'We visited our friends.'),
(158, 'respond to', 'to react or answer', 'Please respond to the email.'),
(159, 'hypothesis', 'an idea that can be tested to see if it is true', 'The researchers tested the hypothesis.'),
(160, 'travel', 'to go from one place to another', 'I love to travel.'),
(161, 'result in', 'to cause a particular result', 'The change resulted in higher costs.'),
(162, 'implicit', 'suggested without being directly stated', 'The criticism was implicit.'),
(163, 'drive', 'to control a car', 'She drives to work every day.'),
(164, 'review', 'to examine something carefully', 'Let''s review the proposal.'),
(165, 'inherent', 'existing as a natural part of something', 'The process has inherent risks.'),
(166, 'walk', 'to move on foot', 'I walk to the station.'),
(167, 'solve', 'to find an answer to a problem', 'We need to solve this issue.'),
(168, 'inevitable', 'certain to happen and impossible to avoid', 'Some change is inevitable.'),
(169, 'run', 'to move quickly on foot', 'He runs every morning.'),
(170, 'suggest', 'to put forward an idea', 'I suggest reviewing the data.'),
(171, 'infer', 'to reach a conclusion from evidence', 'We can infer the cause from the data.'),
(172, 'swim', 'to move through water', 'We swim at the weekend.'),
(173, 'support', 'to help something succeed or to provide evidence for it', 'The results support our conclusion.'),
(174, 'integral', 'necessary to make a whole complete', 'Trust is integral to the relationship.'),
(175, 'play', 'to take part in a game or sport', 'The children play outside.'),
(176, 'treat', 'to behave toward someone or something in a particular way', 'We should treat customers fairly.'),
(177, 'legitimate', 'reasonable, lawful, or acceptable', 'That''s a legitimate concern.'),
(178, 'watch', 'to look at something for a period of time', 'We watched a movie.'),
(179, 'achievable', 'possible to reach or complete successfully', 'The goal is achievable.'),
(180, 'likewise', 'in the same way', 'Likewise, the second team improved.'),
(181, 'read', 'to look at and understand written words', 'I read before bed.'),
(182, 'appropriate', 'suitable for a particular situation', 'That response is appropriate.'),
(183, 'magnitude', 'the great size or importance of something', 'We underestimated the magnitude of the problem.'),
(184, 'write', 'to put words on paper or a screen', 'Please write your name here.'),
(185, 'available', 'able to be used or obtained', 'The information is available online.'),
(186, 'mitigate', 'to reduce the harmful effect of something', 'The controls help mitigate risk.'),
(187, 'speak', 'to use your voice to communicate', 'She speaks English well.'),
(188, 'beneficial', 'having a useful or positive effect', 'The change is beneficial to users.'),
(189, 'notwithstanding', 'despite something', 'Notwithstanding the delay, the project succeeded.'),
(190, 'say', 'to produce words when speaking', 'What did he say?'),
(191, 'complex', 'having many connected parts', 'The system is complex.'),
(192, 'nuance', 'a small difference in meaning or expression', 'The translation loses an important nuance.'),
(193, 'tell', 'to give information to someone', 'Tell me the truth.'),
(194, 'confident', 'feeling sure about your ability or decision', 'She feels confident about the presentation.'),
(195, 'objective', 'based on facts rather than personal feelings', 'We need an objective assessment.'),
(196, 'ask', 'to request information', 'Can I ask a question?'),
(197, 'consistent', 'always behaving or happening in a similar way', 'The results are consistent.'),
(198, 'paradigm', 'a model or pattern that shapes how something is understood', 'The industry is experiencing a paradigm shift.'),
(199, 'answer', 'to respond to a question', 'Please answer the phone.'),
(200, 'convenient', 'easy or suitable for a particular purpose', 'Online meetings are convenient.'),
(201, 'perceive', 'to understand or interpret something in a particular way', 'Customers may perceive the change differently.'),
(202, 'call', 'to speak to someone by phone', 'I''ll call you later.'),
(203, 'curious', 'wanting to know more about something', 'I''m curious about the results.'),
(204, 'pertinent', 'directly relevant to the matter being discussed', 'Please provide the pertinent information.'),
(205, 'send', 'to make something go to another person', 'I''ll send the file today.'),
(206, 'flexible', 'able to change according to circumstances', 'We need a flexible schedule.'),
(207, 'plausible', 'seeming reasonable or likely to be true', 'That is a plausible explanation.'),
(208, 'receive', 'to get something that someone sends', 'Did you receive my email?'),
(209, 'formal', 'official or suitable for serious situations', 'The letter has a formal tone.'),
(210, 'precedent', 'an earlier example used as a guide for later cases', 'The decision could set a precedent.'),
(211, 'bring', 'to take something with you to a place', 'Please bring your laptop.'),
(212, 'generally', 'in most cases', 'The process is generally simple.'),
(213, 'predominantly', 'mostly; mainly', 'The audience was predominantly local.'),
(214, 'carry', 'to hold and move something', 'Can you carry this box?'),
(215, 'independent', 'able to work without help', 'She is an independent worker.'),
(216, 'preliminary', 'happening before the main or final stage', 'These are only preliminary results.'),
(217, 'open', 'to move something so it is no longer closed', 'Please open the window.'),
(218, 'likely', 'probable or expected', 'A delay is likely.'),
(219, 'presumably', 'probably, based on what seems reasonable', 'Presumably, the report is ready.'),
(220, 'close', 'to shut something', 'Close the door, please.'),
(221, 'major', 'very important or large', 'This is a major issue.'),
(222, 'profound', 'very great or having a strong effect', 'The change had a profound impact.'),
(223, 'clean', 'to remove dirt from something', 'I clean the kitchen every day.'),
(224, 'minor', 'small or less important', 'It''s only a minor change.'),
(225, 'prohibit', 'to officially forbid something', 'The policy prohibits unauthorized access.'),
(226, 'wash', 'to clean with water', 'Wash your hands before dinner.'),
(227, 'obvious', 'easy to see or understand', 'The answer seems obvious.'),
(228, 'proliferate', 'to increase or spread rapidly', 'The technology has proliferated across industries.'),
(229, 'cook', 'to prepare food by heating it', 'I cook dinner on Sundays.'),
(230, 'overall', 'considering everything', 'Overall, the results were positive.'),
(231, 'prominent', 'important, famous, or easy to notice', 'She is a prominent researcher.'),
(232, 'eat', 'to put food in your mouth and swallow it', 'We eat at home most nights.'),
(233, 'particular', 'specific rather than general', 'We need a particular example.'),
(234, 'prospect', 'the possibility or likelihood of a future event', 'The prospect of growth is encouraging.'),
(235, 'drink', 'to take liquid into your mouth and swallow it', 'I drink plenty of water.'),
(236, 'patient', 'able to wait calmly without becoming annoyed', 'You need to be patient.'),
(237, 'rationale', 'the reasons behind a decision or action', 'The report explains the rationale.'),
(238, 'sleep', 'to rest with your eyes closed', 'I sleep about eight hours.'),
(239, 'practical', 'useful and realistic', 'We need a practical solution.'),
(240, 'refine', 'to improve something by making small changes', 'We refined the process.'),
(241, 'rest', 'to relax after work or activity', 'You should rest today.'),
(242, 'professional', 'showing suitable behavior at work', 'His response was professional.'),
(243, 'reinforce', 'to strengthen an idea, behavior, or structure', 'The training reinforced good practices.'),
(244, 'feel', 'to experience an emotion or physical condition', 'I feel tired today.'),
(245, 'reliable', 'able to be trusted to work well', 'We need a reliable system.'),
(246, 'reluctant', 'unwilling or hesitant', 'He was reluctant to change the plan.'),
(247, 'look', 'to direct your eyes somewhere', 'Look over there.'),
(248, 'relevant', 'closely connected with the topic', 'Please include relevant information.'),
(249, 'resilient', 'able to recover quickly from difficulty', 'The organization proved resilient.'),
(250, 'seem', 'to appear to be true', 'You seem busy today.'),
(251, 'responsible', 'having a duty to deal with something', 'She is responsible for the budget.'),
(252, 'rigorous', 'very thorough and careful', 'The study used rigorous methods.'),
(253, 'happen', 'to take place', 'What happened yesterday?'),
(254, 'specific', 'clearly defined and not general', 'Can you give a specific example?'),
(255, 'robust', 'strong and able to work well under difficult conditions', 'We need a robust system.'),
(256, 'try', 'to make an effort to do something', 'I''ll try again.'),
(257, 'suitable', 'right for a particular purpose', 'This tool is suitable for beginners.'),
(258, 'scrutinize', 'to examine something very carefully', 'The auditors scrutinized the records.'),
(259, 'hope', 'to want something to happen', 'I hope everything goes well.'),
(260, 'typical', 'usual or expected for a person or situation', 'That is a typical response.'),
(261, 'subsequent', 'happening after something else', 'Subsequent analysis revealed an error.'),
(262, 'plan', 'to decide what you will do', 'We plan our week on Sunday.'),
(263, 'unusual', 'not common or expected', 'The result was unusual.'),
(264, 'substantiate', 'to support a claim with evidence', 'The data substantiates the argument.'),
(265, 'decide', 'to choose after thinking', 'We need to decide today.'),
(266, 'urgent', 'needing immediate attention', 'This is an urgent request.'),
(267, 'sufficient', 'enough for a particular purpose', 'We have sufficient evidence to proceed.'),
(268, 'agree', 'to have the same opinion', 'I agree with you.'),
(269, 'willing', 'prepared to do something', 'She is willing to help.'),
(270, 'tentative', 'not certain or final', 'They reached a tentative agreement.'),
(271, 'believe', 'to think that something is true', 'I believe her story.'),
(272, 'accurately', 'without mistakes', 'The data was recorded accurately.'),
(273, 'thereby', 'as a result of doing something', 'The update reduced errors, thereby improving quality.'),
(274, 'enjoy', 'to get pleasure from something', 'I enjoy working with people.'),
(275, 'apparently', 'as far as can be understood from available information', 'Apparently, the meeting was moved.'),
(276, 'therefore', 'for that reason', 'The sample was small; therefore, the result is limited.'),
(277, 'prefer', 'to like one thing more than another', 'I prefer tea to coffee.'),
(278, 'basically', 'in the simplest or most important way', 'Basically, we need more time.'),
(279, 'undermine', 'to gradually weaken confidence or effectiveness', 'The inconsistency undermined trust.'),
(280, 'usually', 'in most cases or times', 'We usually eat at home.'),
(281, 'clearly', 'in a way that is easy to understand', 'She explained the process clearly.'),
(282, 'unprecedented', 'never having happened before', 'The situation was unprecedented.'),
(283, 'often', 'many times', 'I often work late.'),
(284, 'currently', 'at the present time', 'The system is currently unavailable.'),
(285, 'viable', 'capable of working successfully', 'We need a viable business model.'),
(286, 'sometimes', 'on some occasions', 'I sometimes walk to work.'),
(287, 'eventually', 'in the end, after some time', 'We eventually found a solution.'),
(288, 'vulnerable', 'easily harmed or affected', 'Small firms are vulnerable to shocks.'),
(289, 'never', 'not at any time', 'I''ve never been there.'),
(290, 'frequently', 'often', 'The software is frequently updated.'),
(291, 'whereas', 'while showing a contrast', 'The first option is cheaper, whereas the second is faster.'),
(292, 'always', 'at all times or on every occasion', 'She always checks her email.'),
(293, 'gradually', 'slowly over time', 'The situation gradually improved.'),
(294, 'whereby', 'by which or through which', 'They created a system whereby users can report issues.'),
(295, 'already', 'before now or earlier than expected', 'I''ve already finished.'),
(296, 'hardly', 'almost not', 'I could hardly hear him.'),
(297, 'withstand', 'to resist or survive something difficult', 'The structure can withstand heavy winds.'),
(298, 'still', 'continuing until now', 'Are you still working?'),
(299, 'immediately', 'at once', 'Please reply immediately.'),
(300, 'yield', 'to produce a result or amount', 'The strategy yielded strong results.'),
(301, 'yet', 'until now, usually in questions or negatives', 'I haven''t finished yet.'),
(302, 'instead', 'as an alternative', 'We used email instead.'),
(303, 'accountability', 'responsibility for actions and decisions', 'Clear accountability improves trust.'),
(304, 'almost', 'very nearly', 'I''m almost ready.'),
(305, 'nearly', 'almost', 'The project is nearly finished.'),
(306, 'allocation', 'the distribution of resources for a particular purpose', 'Resource allocation is a key concern.'),
(307, 'maybe', 'possibly', 'Maybe I''ll call tonight.'),
(308, 'occasionally', 'sometimes', 'We occasionally work late.'),
(309, 'benchmark', 'a standard used for comparison', 'We use industry data as a benchmark.'),
(310, 'probably', 'very likely', 'It will probably rain later.'),
(311, 'particularly', 'especially', 'This issue is particularly important.'),
(312, 'bottleneck', 'a point in a process where progress slows because capacity is limited', 'Approval is the main bottleneck.'),
(313, 'enough', 'as much as is needed', 'Do we have enough time?'),
(314, 'probably', 'very likely', 'She''ll probably arrive soon.'),
(315, 'compliance', 'the act of following rules or requirements', 'The company must ensure compliance.'),
(316, 'another', 'one more or a different one', 'Can I have another coffee?'),
(317, 'recently', 'not long ago', 'We recently changed the process.'),
(318, 'convergence', 'the process of becoming more similar or coming together', 'We observed convergence between the two approaches.'),
(319, 'different', 'not the same', 'We have different ideas.'),
(320, 'roughly', 'approximately', 'It takes roughly two hours.'),
(321, 'credibility', 'the quality of being trusted or believed', 'The source''s credibility is important.'),
(322, 'same', 'not different', 'We chose the same hotel.'),
(323, 'significantly', 'in an important or noticeable way', 'Costs increased significantly.'),
(324, 'discretion', 'the freedom to decide what should be done in a situation', 'Managers have discretion in minor cases.'),
(325, 'easy', 'not difficult', 'The exercise was easy.'),
(326, 'similarly', 'in a similar way', 'Similarly, the second team improved.'),
(327, 'feasibility', 'the possibility that something can be done successfully', 'We are studying the project''s feasibility.'),
(328, 'difficult', 'not easy to do or understand', 'This question is difficult.'),
(329, 'therefore', 'for that reason', 'The data was incomplete; therefore, we waited.'),
(330, 'governance', 'the system by which an organization is directed and controlled', 'Good governance supports accountability.'),
(331, 'early', 'before the usual time', 'I arrived early today.'),
(332, 'although', 'despite the fact that', 'Although it was late, we continued.'),
(333, 'incentive', 'something that encourages a person to act', 'The bonus is an incentive to improve performance.'),
(334, 'late', 'after the expected time', 'The train was late.'),
(335, 'as soon as', 'immediately after', 'Call me as soon as you arrive.'),
(336, 'inequality', 'an unfair difference in status, opportunity, or resources', 'The policy aims to reduce inequality.'),
(337, 'busy', 'having a lot to do', 'I''m busy this afternoon.'),
(338, 'because of', 'as a result of', 'The flight was delayed because of the storm.'),
(339, 'insight', 'a useful and deep understanding of something', 'The survey provided an important insight.'),
(340, 'free', 'not busy or not costing money', 'Are you free tonight?'),
(341, 'even though', 'despite the fact that', 'Even though it was difficult, we finished.'),
(342, 'integrity', 'honesty and strong moral principles', 'The process requires integrity.'),
(343, 'ready', 'prepared for something', 'Are you ready to start?'),
(344, 'in addition', 'also', 'In addition, we need more staff.'),
(345, 'intervention', 'an action intended to change a situation', 'Early intervention prevented a larger problem.'),
(346, 'safe', 'not dangerous', 'This area is safe.'),
(347, 'in advance', 'before something happens', 'Please book in advance.'),
(348, 'legislation', 'laws made or considered by a government', 'The company is monitoring new legislation.'),
(349, 'dangerous', 'likely to cause harm', 'That road is dangerous.'),
(350, 'in general', 'usually or overall', 'In general, customers prefer simple solutions.'),
(351, 'liability', 'legal responsibility for something, especially costs or damage', 'The company may face liability.'),
(352, 'important', 'having great value or meaning', 'This meeting is important.'),
(353, 'in the end', 'finally, after everything', 'In the end, we chose the cheaper option.'),
(354, 'mediation', 'a process in which a neutral person helps others reach an agreement', 'The dispute went to mediation.'),
(355, 'useful', 'helpful for a particular purpose', 'This tool is useful.'),
(356, 'on time', 'at the planned time', 'She arrived on time.'),
(357, 'methodology', 'a system of methods used in a field or study', 'The report explains the research methodology.'),
(358, 'interesting', 'keeping your attention because it is useful or unusual', 'The book is interesting.'),
(359, 'for a while', 'for a period of time', 'Let''s wait here for a while.'),
(360, 'mitigation', 'the action of reducing the harmful effects of something', 'The plan includes risk mitigation.'),
(361, 'boring', 'not interesting', 'The lecture was boring.'),
(362, 'at least', 'not less than a particular amount', 'It will take at least an hour.'),
(363, 'notion', 'an idea, belief, or understanding', 'The notion that success is easy is misleading.'),
(364, 'friendly', 'kind and pleasant', 'Our new neighbor is friendly.'),
(365, 'by the way', 'used to introduce another topic', 'By the way, did you call Ana?')
on conflict (day_index) do update set
  term = excluded.term,
  definition = excluded.definition,
  example = excluded.example;

-- ==========================================================
-- 2) ONBOARDING (pop-up de boas-vindas no primeiro acesso)
-- ==========================================================
alter table public.profiles
  add column if not exists has_seen_onboarding boolean not null default false;

-- ==========================================================
-- 3) MODO ESCURO (preferência salva no perfil, acompanha o aluno em qualquer aparelho)
-- ==========================================================
alter table public.profiles
  add column if not exists preferred_theme text not null default 'light' check (preferred_theme in ('light','dark'));
